version: "3.7"
services:
  projeto_etb_spring:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: projeto_etb
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - dev-network

  pgadmin-docker:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@email.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - "5050:80"
    depends_on:
      - projeto_etb_spring
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge